// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package userproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInMethod int32

const (
	SignInMethod_EMAIL SignInMethod = 0
	SignInMethod_PHONE SignInMethod = 1
)

var SignInMethod_name = map[int32]string{
	0: "EMAIL",
	1: "PHONE",
}

var SignInMethod_value = map[string]int32{
	"EMAIL": 0,
	"PHONE": 1,
}

func (x SignInMethod) String() string {
	return proto.EnumName(SignInMethod_name, int32(x))
}

func (SignInMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type VerifyState int32

const (
	VerifyState_SUCCESS VerifyState = 0
	VerifyState_REFRESH VerifyState = 1
	VerifyState_ILLEGAL VerifyState = 2
)

var VerifyState_name = map[int32]string{
	0: "SUCCESS",
	1: "REFRESH",
	2: "ILLEGAL",
}

var VerifyState_value = map[string]int32{
	"SUCCESS": 0,
	"REFRESH": 1,
	"ILLEGAL": 2,
}

func (x VerifyState) String() string {
	return proto.EnumName(VerifyState_name, int32(x))
}

func (VerifyState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

type Acknowledgement struct {
	Acknowledgement      string   `protobuf:"bytes,1,opt,name=acknowledgement,proto3" json:"acknowledgement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Acknowledgement) Reset()         { *m = Acknowledgement{} }
func (m *Acknowledgement) String() string { return proto.CompactTextString(m) }
func (*Acknowledgement) ProtoMessage()    {}
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Acknowledgement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Acknowledgement.Unmarshal(m, b)
}
func (m *Acknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Acknowledgement.Marshal(b, m, deterministic)
}
func (m *Acknowledgement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Acknowledgement.Merge(m, src)
}
func (m *Acknowledgement) XXX_Size() int {
	return xxx_messageInfo_Acknowledgement.Size(m)
}
func (m *Acknowledgement) XXX_DiscardUnknown() {
	xxx_messageInfo_Acknowledgement.DiscardUnknown(m)
}

var xxx_messageInfo_Acknowledgement proto.InternalMessageInfo

func (m *Acknowledgement) GetAcknowledgement() string {
	if m != nil {
		return m.Acknowledgement
	}
	return ""
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Ic                   string   `protobuf:"bytes,4,opt,name=ic,proto3" json:"ic,omitempty"`
	EmailValidation      bool     `protobuf:"varint,5,opt,name=email_validation,json=emailValidation,proto3" json:"email_validation,omitempty"`
	PhoneValidation      bool     `protobuf:"varint,6,opt,name=phone_validation,json=phoneValidation,proto3" json:"phone_validation,omitempty"`
	IcValidation         bool     `protobuf:"varint,7,opt,name=ic_validation,json=icValidation,proto3" json:"ic_validation,omitempty"`
	Year                 uint32   `protobuf:"varint,8,opt,name=year,proto3" json:"year,omitempty"`
	Month                uint32   `protobuf:"varint,9,opt,name=month,proto3" json:"month,omitempty"`
	Day                  uint32   `protobuf:"varint,10,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetIc() string {
	if m != nil {
		return m.Ic
	}
	return ""
}

func (m *User) GetEmailValidation() bool {
	if m != nil {
		return m.EmailValidation
	}
	return false
}

func (m *User) GetPhoneValidation() bool {
	if m != nil {
		return m.PhoneValidation
	}
	return false
}

func (m *User) GetIcValidation() bool {
	if m != nil {
		return m.IcValidation
	}
	return false
}

func (m *User) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *User) GetMonth() uint32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *User) GetDay() uint32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type UpdateUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Ic                   string   `protobuf:"bytes,4,opt,name=ic,proto3" json:"ic,omitempty"`
	Year                 int32    `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,6,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,7,opt,name=day,proto3" json:"day,omitempty"`
	Password             string   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUser) Reset()         { *m = UpdateUser{} }
func (m *UpdateUser) String() string { return proto.CompactTextString(m) }
func (*UpdateUser) ProtoMessage()    {}
func (*UpdateUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UpdateUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUser.Unmarshal(m, b)
}
func (m *UpdateUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUser.Marshal(b, m, deterministic)
}
func (m *UpdateUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUser.Merge(m, src)
}
func (m *UpdateUser) XXX_Size() int {
	return xxx_messageInfo_UpdateUser.Size(m)
}
func (m *UpdateUser) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUser.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUser proto.InternalMessageInfo

func (m *UpdateUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUser) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateUser) GetIc() string {
	if m != nil {
		return m.Ic
	}
	return ""
}

func (m *UpdateUser) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *UpdateUser) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *UpdateUser) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *UpdateUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetItQECRegister struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItQECRegister) Reset()         { *m = GetItQECRegister{} }
func (m *GetItQECRegister) String() string { return proto.CompactTextString(m) }
func (*GetItQECRegister) ProtoMessage()    {}
func (*GetItQECRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *GetItQECRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItQECRegister.Unmarshal(m, b)
}
func (m *GetItQECRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItQECRegister.Marshal(b, m, deterministic)
}
func (m *GetItQECRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItQECRegister.Merge(m, src)
}
func (m *GetItQECRegister) XXX_Size() int {
	return xxx_messageInfo_GetItQECRegister.Size(m)
}
func (m *GetItQECRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItQECRegister.DiscardUnknown(m)
}

var xxx_messageInfo_GetItQECRegister proto.InternalMessageInfo

func (m *GetItQECRegister) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *GetItQECRegister) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetItQECRegister) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type VerifyRequest struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *VerifyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type VerifyResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func (m *VerifyResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("userproto.SignInMethod", SignInMethod_name, SignInMethod_value)
	proto.RegisterEnum("userproto.VerifyState", VerifyState_name, VerifyState_value)
	proto.RegisterType((*Acknowledgement)(nil), "userproto.Acknowledgement")
	proto.RegisterType((*User)(nil), "userproto.User")
	proto.RegisterType((*UpdateUser)(nil), "userproto.UpdateUser")
	proto.RegisterType((*GetItQECRegister)(nil), "userproto.GetItQECRegister")
	proto.RegisterType((*VerifyRequest)(nil), "userproto.VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "userproto.VerifyResponse")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 812 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4f, 0x73, 0xdb, 0x44,
	0x14, 0x8f, 0x64, 0xc7, 0xae, 0x5f, 0xfe, 0x58, 0xb3, 0x49, 0x33, 0xaa, 0xca, 0x41, 0x23, 0x7a,
	0x08, 0x1e, 0x2a, 0x95, 0x34, 0xa7, 0xf4, 0x82, 0x63, 0x44, 0x6b, 0xc6, 0x81, 0x22, 0xe3, 0x30,
	0xc3, 0xa5, 0xa3, 0x48, 0xaf, 0xf2, 0x82, 0xb5, 0xab, 0x6a, 0xd7, 0x71, 0x7d, 0xe5, 0xce, 0x05,
	0x6e, 0x7c, 0x0e, 0xae, 0x7c, 0x0a, 0xbe, 0x02, 0x9f, 0x80, 0x2f, 0x00, 0xb3, 0x2b, 0x3b, 0x55,
	0x4c, 0x86, 0x43, 0x67, 0xb8, 0xd8, 0xef, 0xfd, 0xde, 0x6f, 0x7f, 0xfa, 0xed, 0xdb, 0xb7, 0x0b,
	0x30, 0x17, 0x58, 0xfa, 0x45, 0xc9, 0x25, 0x27, 0x1d, 0x15, 0xeb, 0xd0, 0xf9, 0x20, 0xe3, 0x3c,
	0x9b, 0x61, 0x10, 0x17, 0x34, 0x88, 0x19, 0xe3, 0x32, 0x96, 0x94, 0x33, 0x51, 0x11, 0x9d, 0x8f,
	0xf5, 0x5f, 0xf2, 0x38, 0x43, 0xf6, 0x58, 0x2c, 0xe2, 0x2c, 0xc3, 0x32, 0xe0, 0x85, 0x66, 0xdc,
	0xc1, 0x7e, 0xb8, 0xd2, 0xd2, 0xd9, 0xd5, 0xfc, 0x75, 0x80, 0x79, 0x21, 0x97, 0x55, 0xd1, 0x7b,
	0x06, 0xdd, 0x7e, 0xf2, 0x03, 0xe3, 0x8b, 0x19, 0xa6, 0x19, 0xe6, 0xc8, 0x24, 0x39, 0x86, 0x6e,
	0x7c, 0x1b, 0xb2, 0x0d, 0xd7, 0x38, 0xee, 0x44, 0x9b, 0xb0, 0xf7, 0x93, 0x09, 0xcd, 0x89, 0xc0,
	0x92, 0x10, 0x68, 0xb2, 0x38, 0xc7, 0x15, 0x4f, 0xc7, 0xe4, 0x10, 0xb6, 0x31, 0x8f, 0xe9, 0xcc,
	0x36, 0x35, 0x58, 0x25, 0x0a, 0x2d, 0xa6, 0x9c, 0xa1, 0xdd, 0xa8, 0x50, 0x9d, 0x90, 0x7d, 0x30,
	0x69, 0x62, 0x37, 0x35, 0x64, 0xd2, 0x84, 0x7c, 0x04, 0x96, 0xa6, 0xbf, 0xba, 0x8e, 0x67, 0x34,
	0xd5, 0xbb, 0xb1, 0xb7, 0x5d, 0xe3, 0xf8, 0x5e, 0xd4, 0xd5, 0xf8, 0xe5, 0x0d, 0xac, 0xa8, 0x5a,
	0xa3, 0x4e, 0x6d, 0x55, 0x54, 0x8d, 0xd7, 0xa8, 0x1f, 0xc2, 0x1e, 0x4d, 0xea, 0xbc, 0xb6, 0xe6,
	0xed, 0xd2, 0xa4, 0x46, 0x22, 0xd0, 0x5c, 0x62, 0x5c, 0xda, 0xf7, 0x5c, 0xe3, 0x78, 0x2f, 0xd2,
	0xb1, 0x32, 0x9d, 0x73, 0x26, 0xa7, 0x76, 0x47, 0x83, 0x55, 0x42, 0x2c, 0x68, 0xa4, 0xf1, 0xd2,
	0x06, 0x8d, 0xa9, 0xd0, 0xfb, 0xcd, 0x00, 0x98, 0x14, 0x69, 0x2c, 0xf1, 0x7f, 0xe9, 0xca, 0xda,
	0x9a, 0xea, 0xc4, 0xf6, 0xa6, 0xb5, 0x96, 0x06, 0x6f, 0x5b, 0x6b, 0x6b, 0x4c, 0x85, 0xc4, 0x81,
	0x7b, 0x45, 0x2c, 0xc4, 0x82, 0x97, 0xa9, 0xde, 0x5a, 0x27, 0xba, 0xc9, 0xbd, 0x4b, 0xb0, 0x9e,
	0xa3, 0x1c, 0xca, 0xaf, 0xc3, 0x41, 0x84, 0x19, 0x15, 0x12, 0xcb, 0x77, 0x8e, 0x8c, 0xba, 0xa3,
	0xbb, 0xdd, 0x1f, 0x41, 0x4b, 0x4d, 0xee, 0xf0, 0xb3, 0x95, 0xfd, 0x55, 0xe6, 0x3d, 0x85, 0xbd,
	0x4b, 0x2c, 0xe9, 0xeb, 0x65, 0x84, 0x6f, 0xe6, 0x28, 0xa4, 0xda, 0x40, 0x1a, 0xcb, 0x78, 0xdd,
	0x10, 0x15, 0xeb, 0x4d, 0xa6, 0x2b, 0x3d, 0x93, 0xa6, 0xde, 0x23, 0xd8, 0x5f, 0x2f, 0x12, 0x05,
	0x67, 0x02, 0xef, 0x5a, 0xd5, 0x7b, 0x04, 0xbb, 0x63, 0x9a, 0xb1, 0x21, 0xbb, 0x40, 0x39, 0xe5,
	0x29, 0xe9, 0xc0, 0x76, 0x78, 0xd1, 0x1f, 0x8e, 0xac, 0x2d, 0x15, 0xbe, 0x7c, 0xf1, 0xd5, 0x97,
	0xa1, 0x65, 0xf4, 0x4e, 0x61, 0xa7, 0xd2, 0x1a, 0xcb, 0x58, 0x22, 0xd9, 0x81, 0xf6, 0x78, 0x32,
	0x18, 0x84, 0xe3, 0xb1, 0xb5, 0xa5, 0x92, 0x28, 0xfc, 0x3c, 0x0a, 0xc7, 0x2f, 0x2c, 0x43, 0x25,
	0xc3, 0xd1, 0x28, 0x7c, 0xde, 0x1f, 0x59, 0xe6, 0xc9, 0xdf, 0x0d, 0xd8, 0x51, 0xe7, 0x37, 0xc6,
	0xf2, 0x9a, 0x26, 0x48, 0x06, 0xd0, 0x12, 0x34, 0x63, 0x93, 0x82, 0x3c, 0xf4, 0x6f, 0x6e, 0xa8,
	0xbf, 0xd9, 0x31, 0xc7, 0xa9, 0x15, 0x37, 0xae, 0x94, 0xb7, 0x45, 0xbe, 0x80, 0x76, 0x86, 0x52,
	0x8f, 0xc5, 0x91, 0x5f, 0x5d, 0x48, 0x7f, 0x7d, 0x21, 0xfd, 0x50, 0x5d, 0x48, 0xa7, 0x5b, 0x13,
	0x50, 0x44, 0xef, 0xe8, 0xc7, 0x3f, 0xfe, 0xfc, 0xc5, 0xb4, 0xc8, 0xbe, 0x7e, 0x06, 0x54, 0x51,
	0xff, 0x90, 0x6f, 0x00, 0xe6, 0xef, 0xa6, 0x6c, 0x73, 0xd9, 0x7f, 0x1a, 0x79, 0xa0, 0x25, 0x0f,
	0x9c, 0x0d, 0xc9, 0x33, 0xa3, 0x47, 0xbe, 0x83, 0x9d, 0x6b, 0xdd, 0xac, 0x50, 0x1f, 0xaa, 0x5d,
	0x53, 0xb9, 0x75, 0x8a, 0xce, 0x83, 0x3b, 0x2a, 0xd5, 0x51, 0xd5, 0x1c, 0xeb, 0xc9, 0x10, 0x41,
	0xa5, 0x48, 0x5e, 0xc1, 0x6e, 0x15, 0x5d, 0xf0, 0x2b, 0x3a, 0xc3, 0xf7, 0x13, 0x77, 0xb4, 0xf8,
	0xa1, 0xd7, 0x0d, 0x72, 0xad, 0xb2, 0x56, 0x57, 0xe6, 0x47, 0x70, 0x10, 0xa7, 0x39, 0x65, 0xd5,
	0x92, 0x61, 0x8a, 0x4c, 0x52, 0xb9, 0x7c, 0xbf, 0xef, 0x6c, 0x9d, 0xff, 0x65, 0xfc, 0xdc, 0xff,
	0xdd, 0x20, 0xdf, 0xc2, 0xae, 0x6a, 0xa8, 0x2b, 0xaa, 0x41, 0xf0, 0xce, 0xe1, 0x7e, 0x86, 0x92,
	0xca, 0x37, 0x98, 0xb8, 0xf3, 0x5a, 0x81, 0x1c, 0x4e, 0xa5, 0x2c, 0xc4, 0x59, 0x10, 0xac, 0xcb,
	0x7e, 0xc2, 0x73, 0xe7, 0x60, 0xf1, 0xd6, 0x1f, 0x4c, 0x11, 0x3f, 0x55, 0xe8, 0x0a, 0x3c, 0x69,
	0x7c, 0xe2, 0x3f, 0xe9, 0x19, 0xe6, 0x89, 0x15, 0x17, 0xc5, 0x8c, 0x26, 0xfa, 0xcd, 0x09, 0xbe,
	0x17, 0x9c, 0x9d, 0xfd, 0x0b, 0x89, 0x9e, 0x41, 0xe3, 0xf4, 0xc9, 0x29, 0x39, 0x85, 0x5e, 0x84,
	0x72, 0x5e, 0x32, 0x4c, 0xdd, 0xc5, 0x14, 0x99, 0x2b, 0xa7, 0xe8, 0x96, 0x28, 0xf8, 0xbc, 0x4c,
	0xd0, 0x4d, 0x39, 0x0a, 0x97, 0x71, 0xe9, 0xe2, 0x5b, 0x2a, 0xa4, 0x4f, 0x5a, 0xd0, 0xfc, 0xd5,
	0x34, 0xda, 0x70, 0x94, 0xf0, 0xdc, 0xbf, 0xf1, 0x33, 0x59, 0x6f, 0xf6, 0xfc, 0x7e, 0x7f, 0x2e,
	0xa7, 0xaa, 0x3d, 0xd5, 0x97, 0x56, 0x43, 0xfe, 0xd2, 0xb8, 0x6a, 0xe9, 0xfa, 0xd3, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xe2, 0xdd, 0x6c, 0x4a, 0x92, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// reuqest response
	SignUp(ctx context.Context, in *GetItQECRegister, opts ...grpc.CallOption) (*Acknowledgement, error)
	GetUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Acknowledgement, error)
	VerifyEmail(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	VerifyMobile(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	AdminVerifyIdentity(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) SignUp(ctx context.Context, in *GetItQECRegister, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/userproto.UserService/signUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/userproto.UserService/getUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/userproto.UserService/updateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) VerifyEmail(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/verifyEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) VerifyMobile(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/verifyMobile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AdminVerifyIdentity(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/adminVerifyIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// reuqest response
	SignUp(context.Context, *GetItQECRegister) (*Acknowledgement, error)
	GetUser(context.Context, *empty.Empty) (*User, error)
	UpdateUser(context.Context, *User) (*Acknowledgement, error)
	VerifyEmail(context.Context, *VerifyRequest) (*VerifyResponse, error)
	VerifyMobile(context.Context, *VerifyRequest) (*VerifyResponse, error)
	AdminVerifyIdentity(context.Context, *VerifyRequest) (*VerifyResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) SignUp(ctx context.Context, req *GetItQECRegister) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *empty.Empty) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *User) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) VerifyEmail(ctx context.Context, req *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyEmail not implemented")
}
func (*UnimplementedUserServiceServer) VerifyMobile(ctx context.Context, req *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyMobile not implemented")
}
func (*UnimplementedUserServiceServer) AdminVerifyIdentity(ctx context.Context, req *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminVerifyIdentity not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItQECRegister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignUp(ctx, req.(*GetItQECRegister))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/VerifyEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VerifyEmail(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_VerifyMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VerifyMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/VerifyMobile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VerifyMobile(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AdminVerifyIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AdminVerifyIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/AdminVerifyIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AdminVerifyIdentity(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userproto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "signUp",
			Handler:    _UserService_SignUp_Handler,
		},
		{
			MethodName: "getUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "updateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "verifyEmail",
			Handler:    _UserService_VerifyEmail_Handler,
		},
		{
			MethodName: "verifyMobile",
			Handler:    _UserService_VerifyMobile_Handler,
		},
		{
			MethodName: "adminVerifyIdentity",
			Handler:    _UserService_AdminVerifyIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
